theme: jekyll-theme-slate
title: Protty's place
description: Another medium to spew thoughts

logo: "https://avatars1.githubusercontent.com/u/45520026"
image: "https://avatars1.githubusercontent.com/u/45520026"